sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5bfce3ef6a29f96a2ded
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false