sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  # This is needed until Travis #4629 is fixed (https://github.com/travis-ci/travis-ci/issues/4629)
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://dl.bintray.com/buremba/maven/|g' ~/.m2/settings.xml
install: ./mvnw install -DskipTests
addons:
  apt:
    packages:
      - oracle-java8-installer
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5bfce3ef6a29f96a2ded
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
after_success:
- >
  [ "$TRAVIS_BRANCH" == "master" ]
  && curl -X POST -H "Content-Type: application/json"
  --data '{"docker_tag_name": ${TRAVIS_TAG:=latest}}'
  https://registry.hub.docker.com/u/buremba/rakam/trigger/$DOCKER_HUB_TOKEN/