name: rakam
image: ubuntu-14-04-x64
min_size: 1gb
packages:
  - docker-engine
config:
  runcmd:
    - docker run -d --name rakam-db -e POSTGRES_PASSWORD=dummy -e POSTGRES_USER=rakam postgres:9.6.1 && docker run --link rakam-db --name rakam -p 9999:9999 -e RAKAM_CONFIG_LOCK-KEY=mylockkey buremba/rakam