version: '2'
services:
  db:
    image: postgres:9.5.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dummy
      - POSTGRES_USER=rakam
  api:
    build: .
    ports:
      - "9998:9998"
    depends_on:
      - db